version: 2

updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      day: friday
      interval: 'weekly'
      time: '00:00'
      timezone: 'UTC'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      day: friday
      interval: 'weekly'
      time: '00:00'
      timezone: 'UTC'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      day: friday
      interval: 'weekly'
      time: '00:00'
      timezone: 'UTC'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: friday
      interval: 'weekly'
      time: '00:00'
      timezone: 'UTC'
